function [controllerBlock, getStateBlock, rxBlocks, txBlocks] = addEthercatIo(target)
modelName = char(target.ModelName);
ethercatCfg = target.Ethercat;

initBlock = [modelName '/EtherCAT Init'];
add_block('slrealtimeethercatlib/EtherCAT Init', initBlock, 'Position', [40 40 260 95]);
set_param(initBlock, ...
    'config_file', char(target.EniFile), ...
    'device_id', num2str(ethercatCfg.DeviceIndex), ...
    'portnum', num2str(ethercatCfg.PortNumber), ...
    'initstate', char(ethercatCfg.InitStateValue), ...
    'dctuning', char(ethercatCfg.DCTuningValue), ...
    'enaDC', 'on', ...
    'DCMode', char(ethercatCfg.DCModeValue), ...
    'sample_time', num2str(ethercatCfg.SampleTime));

getStateBlock = [modelName '/EtherCAT Get State'];
add_block('slrealtimeethercatlib/EtherCAT Get State', getStateBlock, 'Position', [40 140 260 185]);
set_param(getStateBlock, ...
    'device_id', num2str(ethercatCfg.DeviceIndex), ...
    'sample_time', num2str(ethercatCfg.SampleTime));

rxBlocks = struct();
for k = 1:numel(target.PdoMap.Rx)
    sig = target.PdoMap.Rx(k);
    block = [modelName '/' char(sig.BlockName)];
    add_block('slrealtimeethercatlib/EtherCAT PDO Receive', block, ...
        'Position', [40 230 + (k - 1) * 55 330 265 + (k - 1) * 55]);
    set_param(block, ...
        'sig_name', char(sig.SignalName), ...
        'sig_offset', num2str(sig.Offset), ...
        'sig_type', char(sig.DataType), ...
        'type_size', num2str(sig.TypeSize), ...
        'sig_dim', '1', ...
        'device_id', num2str(ethercatCfg.DeviceIndex), ...
        'sample_time', num2str(ethercatCfg.SampleTime));
    rxBlocks.(char(sig.Key)) = block;
end

controllerBlock = sgv2.internal.addSequenceController(target);

add_line(modelName, [get_param(getStateBlock, 'Name') '/1'], [get_param(controllerBlock, 'Name') '/1'], 'autorouting', 'on');
add_line(modelName, [get_param(rxBlocks.statusword6041, 'Name') '/1'], [get_param(controllerBlock, 'Name') '/3'], 'autorouting', 'on');
add_line(modelName, [get_param(rxBlocks.errorCode603F, 'Name') '/1'], [get_param(controllerBlock, 'Name') '/4'], 'autorouting', 'on');
add_line(modelName, [get_param(rxBlocks.modeDisplay6061, 'Name') '/1'], [get_param(controllerBlock, 'Name') '/5'], 'autorouting', 'on');
add_line(modelName, [get_param(rxBlocks.velocityActual606C, 'Name') '/1'], [get_param(controllerBlock, 'Name') '/6'], 'autorouting', 'on');

txBlocks = struct();
for k = 1:numel(target.PdoMap.Tx)
    sig = target.PdoMap.Tx(k);
    block = [modelName '/' char(sig.BlockName)];
    add_block('slrealtimeethercatlib/EtherCAT PDO Transmit', block, ...
        'Position', [960 180 + (k - 1) * 55 1250 215 + (k - 1) * 55]);
    set_param(block, ...
        'sig_name', char(sig.SignalName), ...
        'sig_offset', num2str(sig.Offset), ...
        'sig_type', char(sig.DataType), ...
        'type_size', num2str(sig.TypeSize), ...
        'sig_dim', '1', ...
        'device_id', num2str(ethercatCfg.DeviceIndex), ...
        'sample_time', num2str(ethercatCfg.SampleTime));
    txBlocks.(char(sig.Key)) = block;
end

add_line(modelName, [get_param(controllerBlock, 'Name') '/1'], [get_param(txBlocks.controlword6040, 'Name') '/1'], 'autorouting', 'on');
add_line(modelName, [get_param(controllerBlock, 'Name') '/2'], [get_param(txBlocks.targetVelocity60FF, 'Name') '/1'], 'autorouting', 'on');
add_line(modelName, [get_param(controllerBlock, 'Name') '/3'], [get_param(txBlocks.modeOfOperation6060, 'Name') '/1'], 'autorouting', 'on');
add_line(modelName, [get_param(controllerBlock, 'Name') '/4'], [get_param(txBlocks.maxProfileVelocity607F, 'Name') '/1'], 'autorouting', 'on');
end
