function addObservabilityPorts(target, controllerBlock, getStateBlock, rxBlocks, txBlocks, commandBlocks) %#ok<INUSD>
modelName = char(target.ModelName);
signals = { ...
    target.Signals.ActualNetworkState, getStateBlock, 1; ...
    target.Signals.ExpectedNetworkState, commandBlocks.command_expected_network_state, 1; ...
    target.Signals.Statusword6041, rxBlocks.statusword6041, 1; ...
    target.Signals.ErrorCode603F, rxBlocks.errorCode603F, 1; ...
    target.Signals.ModeDisplay6061, rxBlocks.modeDisplay6061, 1; ...
    target.Signals.VelocityActual606C, rxBlocks.velocityActual606C, 1; ...
    target.Signals.DiagCode, controllerBlock, 7; ...
    target.Signals.DiagMessageId, controllerBlock, 8; ...
    target.Signals.DiagLookupGroup, controllerBlock, 9; ...
    target.Signals.DiagLookupHint, controllerBlock, 10; ...
    target.Signals.ReadyToRun, controllerBlock, 5; ...
    target.Signals.AutoStartStep, controllerBlock, 6; ...
    target.Signals.SpeedCommand60FF, commandBlocks.command_speed_command_60ff, 1; ...
    target.Signals.SpeedLimit607F, commandBlocks.command_speed_limit_607f, 1};

for k = 1:size(signals, 1)
    add_block('simulink/Sinks/Out1', [modelName '/' char(signals{k, 1})], ...
        'Position', [1320 40 + (k - 1) * 35 1350 54 + (k - 1) * 35]);
    add_line(modelName, [get_param(signals{k, 2}, 'Name') '/' num2str(signals{k, 3})], ...
        [char(signals{k, 1}) '/1'], 'autorouting', 'on');
end
end
