function referenceBlocks = addPositionReferenceSource(target, controllerBlock, positionActualSourceBlock)
modelName = char(target.ModelName);
sourceBlock = [modelName '/Position Reference Source'];
add_block('simulink/Ports & Subsystems/Subsystem', sourceBlock, ...
    'Position', [300 540 500 700]);

positionValuesBlock = [modelName '/position_reference_values_6064'];
rateValuesBlock = [modelName '/position_rate_reference_values_6064'];
feedforwardEnableBlock = [modelName '/position_reference_feedforward_enabled'];
referencePlayRequestBlock = [modelName '/reference_play_request'];
homeToZeroRequestBlock = [modelName '/home_to_zero_request'];
homeToZeroSpeedBlock = [modelName '/home_to_zero_speed'];
referenceSampleTimeBlock = [modelName '/reference_sample_time'];
referencePositionUnitBlock = [modelName '/reference_position_unit_millimeters_per_count_6064'];

add_block('simulink/Sources/Constant', positionValuesBlock, ...
    'Value', 'SGV2_POSITION_REFERENCE_VALUES_6064', ...
    'OutDataTypeStr', 'int32', ...
    'Position', [80 545 220 575]);
add_block('simulink/Sources/Constant', rateValuesBlock, ...
    'Value', 'SGV2_POSITION_RATE_REFERENCE_VALUES_6064', ...
    'OutDataTypeStr', 'int32', ...
    'Position', [80 595 220 625]);
add_block('simulink/Sources/Constant', feedforwardEnableBlock, ...
    'Value', char(target.Tunables.PositionReferenceFeedforwardEnabled), ...
    'OutDataTypeStr', 'int32', ...
    'Position', [80 645 220 675]);
add_block('simulink/Sources/Constant', referencePlayRequestBlock, ...
    'Value', char(target.Tunables.ReferencePlayRequest), ...
    'OutDataTypeStr', 'int32', ...
    'Position', [80 695 220 725]);
add_block('simulink/Sources/Constant', homeToZeroRequestBlock, ...
    'Value', char(target.Tunables.HomeToZeroRequest), ...
    'OutDataTypeStr', 'int32', ...
    'Position', [80 745 220 775]);
add_block('simulink/Sources/Constant', homeToZeroSpeedBlock, ...
    'Value', char(target.Tunables.HomeToZeroSpeed), ...
    'OutDataTypeStr', 'int32', ...
    'Position', [80 795 220 825]);
add_block('simulink/Sources/Constant', referenceSampleTimeBlock, ...
    'Value', num2str(target.SampleTime), ...
    'OutDataTypeStr', 'double', ...
    'Position', [80 845 220 875]);
add_block('simulink/Sources/Constant', referencePositionUnitBlock, ...
    'Value', char(target.Tunables.PositionUnitMillimetersPerCount6064), ...
    'OutDataTypeStr', 'double', ...
    'Position', [80 895 220 925]);

localBuildReferenceSubsystem(sourceBlock);

sourceHandles = get_param(sourceBlock, 'PortHandles');
positionHandles = get_param(positionValuesBlock, 'PortHandles');
rateHandles = get_param(rateValuesBlock, 'PortHandles');
feedforwardEnableHandles = get_param(feedforwardEnableBlock, 'PortHandles');
referencePlayRequestHandles = get_param(referencePlayRequestBlock, 'PortHandles');
homeToZeroRequestHandles = get_param(homeToZeroRequestBlock, 'PortHandles');
homeToZeroSpeedHandles = get_param(homeToZeroSpeedBlock, 'PortHandles');
referenceSampleTimeHandles = get_param(referenceSampleTimeBlock, 'PortHandles');
referencePositionUnitHandles = get_param(referencePositionUnitBlock, 'PortHandles');
controllerHandles = get_param(controllerBlock, 'PortHandles');
positionActualHandles = get_param(positionActualSourceBlock, 'PortHandles');

add_line(modelName, positionHandles.Outport, sourceHandles.Inport(1), 'autorouting', 'on');
add_line(modelName, rateHandles.Outport, sourceHandles.Inport(2), 'autorouting', 'on');
add_line(modelName, feedforwardEnableHandles.Outport, sourceHandles.Inport(3), 'autorouting', 'on');
add_line(modelName, referencePlayRequestHandles.Outport, sourceHandles.Inport(4), 'autorouting', 'on');
add_line(modelName, homeToZeroRequestHandles.Outport, sourceHandles.Inport(5), 'autorouting', 'on');
add_line(modelName, homeToZeroSpeedHandles.Outport, sourceHandles.Inport(6), 'autorouting', 'on');
add_line(modelName, referenceSampleTimeHandles.Outport, sourceHandles.Inport(7), 'autorouting', 'on');
add_line(modelName, referencePositionUnitHandles.Outport, sourceHandles.Inport(8), 'autorouting', 'on');
add_line(modelName, controllerHandles.Outport(5), sourceHandles.Inport(9), 'autorouting', 'on');
add_line(modelName, positionActualHandles.Outport, sourceHandles.Inport(10), 'autorouting', 'on');

referenceBlocks = struct( ...
    'SourceBlock', sourceBlock, ...
    'PositionReferencePort', 1, ...
    'RateReferencePort', 2, ...
    'PositionCommandPort', 1, ...
    'RateCommandPort', 2);
end

function localBuildReferenceSubsystem(sourceBlock)
lineHandles = find_system(sourceBlock, 'FindAll', 'on', 'Type', 'line');
if ~isempty(lineHandles)
    delete_line(lineHandles);
end

blocks = find_system(sourceBlock, 'SearchDepth', 1, 'Type', 'Block');
for k = 2:numel(blocks)
    delete_block(blocks{k});
end

add_block('simulink/Sources/In1', [sourceBlock '/position_values_6064'], ...
    'Position', [30 45 60 59]);
add_block('simulink/Sources/In1', [sourceBlock '/rate_values_6064'], ...
    'Position', [30 95 60 109]);
add_block('simulink/Sources/In1', [sourceBlock '/feedforward_enabled'], ...
    'Position', [30 145 60 159]);
add_block('simulink/Sources/In1', [sourceBlock '/reference_play_request'], ...
    'Position', [30 195 60 209]);
add_block('simulink/Sources/In1', [sourceBlock '/home_to_zero_request'], ...
    'Position', [30 245 60 259]);
add_block('simulink/Sources/In1', [sourceBlock '/home_to_zero_speed'], ...
    'Position', [30 295 60 309]);
add_block('simulink/Sources/In1', [sourceBlock '/sample_time'], ...
    'Position', [30 345 60 359]);
add_block('simulink/Sources/In1', [sourceBlock '/position_unit_millimeters_per_count_6064'], ...
    'Position', [30 395 60 409]);
add_block('simulink/Sources/In1', [sourceBlock '/ready_to_run'], ...
    'Position', [30 445 60 459]);
add_block('simulink/Sources/In1', [sourceBlock '/position_actual_6064'], ...
    'Position', [30 495 60 509]);
add_block('simulink/Discrete/Unit Delay', [sourceBlock '/sample_index_delay'], ...
    'InitialCondition', '1', ...
    'SampleTime', '-1', ...
    'Position', [110 545 160 575]);
add_block('simulink/Discrete/Unit Delay', [sourceBlock '/base_position_6064_delay'], ...
    'InitialCondition', '0', ...
    'SampleTime', '-1', ...
    'Position', [110 595 160 625]);
add_block('simulink/Discrete/Unit Delay', [sourceBlock '/was_ready_delay'], ...
    'InitialCondition', 'false', ...
    'SampleTime', '-1', ...
    'Position', [110 645 160 675]);
add_block('simulink/Discrete/Unit Delay', [sourceBlock '/was_play_requested_delay'], ...
    'InitialCondition', 'false', ...
    'SampleTime', '-1', ...
    'Position', [110 695 160 725]);
add_block('simulink/Discrete/Unit Delay', [sourceBlock '/last_reference_6064_delay'], ...
    'InitialCondition', '0', ...
    'SampleTime', '-1', ...
    'Position', [110 745 160 775]);
add_block('simulink/Discrete/Unit Delay', [sourceBlock '/has_reference_delay'], ...
    'InitialCondition', 'false', ...
    'SampleTime', '-1', ...
    'Position', [110 795 160 825]);
add_block('simulink/User-Defined Functions/MATLAB Function', [sourceBlock '/reference_step'], ...
    'Position', [220 65 520 405]);
add_block('simulink/Sinks/Out1', [sourceBlock '/position_reference_6064'], ...
    'Position', [610 70 640 84]);
add_block('simulink/Sinks/Out1', [sourceBlock '/position_rate_reference_6064'], ...
    'Position', [610 120 640 134]);

block = [sourceBlock '/reference_step'];
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', block);
chart.Script = sprintf([ ...
    'function [position_ref, rate_ref, next_index, next_base_position, next_was_ready, next_was_play_requested, next_last_reference, next_has_reference] = reference_step(position_values, rate_values, feedforward_enabled, reference_play_request, home_to_zero_request, home_to_zero_speed, sample_time, position_unit_millimeters_per_count_6064, ready_to_run, position_actual, sample_index, base_position, was_ready, was_play_requested, last_reference, has_reference)\n' ...
    '%%#codegen\n' ...
    'state = struct(''SampleIndex'', sample_index, ''BasePosition6064'', int32(base_position), ''WasReady'', logical(was_ready), ''WasPlayRequested'', logical(was_play_requested), ''LastReference6064'', int32(last_reference), ''HasReference'', logical(has_reference));\n' ...
    'result = sgv2.control.computePositionReferenceStep(position_values, rate_values, feedforward_enabled, ready_to_run, position_actual, reference_play_request, home_to_zero_request, home_to_zero_speed, sample_time, position_unit_millimeters_per_count_6064, state);\n' ...
    'position_ref = result.PositionReference6064;\n' ...
    'rate_ref = result.RateReference6064;\n' ...
    'next_index = result.SampleIndexNext;\n' ...
    'next_base_position = result.BasePosition6064Next;\n' ...
    'next_was_ready = result.WasReadyNext;\n' ...
    'next_was_play_requested = result.WasPlayRequestedNext;\n' ...
    'next_last_reference = result.LastReference6064Next;\n' ...
    'next_has_reference = result.HasReferenceNext;\n' ...
    'end\n']);
localConfigureReferenceStepData(chart);

add_line(sourceBlock, 'position_values_6064/1', 'reference_step/1', 'autorouting', 'on');
add_line(sourceBlock, 'rate_values_6064/1', 'reference_step/2', 'autorouting', 'on');
add_line(sourceBlock, 'feedforward_enabled/1', 'reference_step/3', 'autorouting', 'on');
add_line(sourceBlock, 'reference_play_request/1', 'reference_step/4', 'autorouting', 'on');
add_line(sourceBlock, 'home_to_zero_request/1', 'reference_step/5', 'autorouting', 'on');
add_line(sourceBlock, 'home_to_zero_speed/1', 'reference_step/6', 'autorouting', 'on');
add_line(sourceBlock, 'sample_time/1', 'reference_step/7', 'autorouting', 'on');
add_line(sourceBlock, 'position_unit_millimeters_per_count_6064/1', 'reference_step/8', 'autorouting', 'on');
add_line(sourceBlock, 'ready_to_run/1', 'reference_step/9', 'autorouting', 'on');
add_line(sourceBlock, 'position_actual_6064/1', 'reference_step/10', 'autorouting', 'on');
add_line(sourceBlock, 'sample_index_delay/1', 'reference_step/11', 'autorouting', 'on');
add_line(sourceBlock, 'base_position_6064_delay/1', 'reference_step/12', 'autorouting', 'on');
add_line(sourceBlock, 'was_ready_delay/1', 'reference_step/13', 'autorouting', 'on');
add_line(sourceBlock, 'was_play_requested_delay/1', 'reference_step/14', 'autorouting', 'on');
add_line(sourceBlock, 'last_reference_6064_delay/1', 'reference_step/15', 'autorouting', 'on');
add_line(sourceBlock, 'has_reference_delay/1', 'reference_step/16', 'autorouting', 'on');
add_line(sourceBlock, 'reference_step/1', 'position_reference_6064/1', 'autorouting', 'on');
add_line(sourceBlock, 'reference_step/2', 'position_rate_reference_6064/1', 'autorouting', 'on');
add_line(sourceBlock, 'reference_step/3', 'sample_index_delay/1', 'autorouting', 'on');
add_line(sourceBlock, 'reference_step/4', 'base_position_6064_delay/1', 'autorouting', 'on');
add_line(sourceBlock, 'reference_step/5', 'was_ready_delay/1', 'autorouting', 'on');
add_line(sourceBlock, 'reference_step/6', 'was_play_requested_delay/1', 'autorouting', 'on');
add_line(sourceBlock, 'reference_step/7', 'last_reference_6064_delay/1', 'autorouting', 'on');
add_line(sourceBlock, 'reference_step/8', 'has_reference_delay/1', 'autorouting', 'on');
end

function localConfigureReferenceStepData(chart)
localSetChartDataType(chart, 'position_values', 'int32');
localSetChartDataType(chart, 'rate_values', 'int32');
localSetChartDataType(chart, 'feedforward_enabled', 'int32');
localSetChartDataType(chart, 'reference_play_request', 'int32');
localSetChartDataType(chart, 'home_to_zero_request', 'int32');
localSetChartDataType(chart, 'home_to_zero_speed', 'int32');
localSetChartDataType(chart, 'sample_time', 'double');
localSetChartDataType(chart, 'position_unit_millimeters_per_count_6064', 'double');
localSetChartDataType(chart, 'ready_to_run', 'uint8');
localSetChartDataType(chart, 'position_actual', 'int32');
localSetChartDataType(chart, 'sample_index', 'double');
localSetChartDataType(chart, 'base_position', 'int32');
localSetChartDataType(chart, 'was_ready', 'boolean');
localSetChartDataType(chart, 'was_play_requested', 'boolean');
localSetChartDataType(chart, 'last_reference', 'int32');
localSetChartDataType(chart, 'has_reference', 'boolean');
localSetChartDataType(chart, 'position_ref', 'int32');
localSetChartDataType(chart, 'rate_ref', 'int32');
localSetChartDataType(chart, 'next_index', 'double');
localSetChartDataType(chart, 'next_base_position', 'int32');
localSetChartDataType(chart, 'next_was_ready', 'boolean');
localSetChartDataType(chart, 'next_was_play_requested', 'boolean');
localSetChartDataType(chart, 'next_last_reference', 'int32');
localSetChartDataType(chart, 'next_has_reference', 'boolean');
end

function localSetChartDataType(chart, name, dataType)
data = chart.find('-isa', 'Stateflow.Data', 'Name', name);
if isempty(data)
    return;
end
data.Props.Type.Method = 'Built-in';
data.DataType = dataType;
end
