function referenceBlocks = addPositionReferenceSource(target)
modelName = char(target.ModelName);
sourceBlock = [modelName '/Position Reference Source'];
add_block('simulink/Ports & Subsystems/Subsystem', sourceBlock, ...
    'Position', [300 540 500 700]);

positionValuesBlock = [modelName '/position_reference_values_6064'];
rateValuesBlock = [modelName '/position_rate_reference_values_6064'];
feedforwardEnableBlock = [modelName '/position_reference_feedforward_enabled'];

add_block('simulink/Sources/Constant', positionValuesBlock, ...
    'Value', 'SGV2_POSITION_REFERENCE_VALUES_6064', ...
    'OutDataTypeStr', 'int32', ...
    'Position', [80 545 220 575]);
add_block('simulink/Sources/Constant', rateValuesBlock, ...
    'Value', 'SGV2_POSITION_RATE_REFERENCE_VALUES_6064', ...
    'OutDataTypeStr', 'int32', ...
    'Position', [80 595 220 625]);
add_block('simulink/Sources/Constant', feedforwardEnableBlock, ...
    'Value', char(target.Tunables.PositionReferenceFeedforwardEnabled), ...
    'OutDataTypeStr', 'int32', ...
    'Position', [80 645 220 675]);

localBuildReferenceSubsystem(sourceBlock);

sourceHandles = get_param(sourceBlock, 'PortHandles');
positionHandles = get_param(positionValuesBlock, 'PortHandles');
rateHandles = get_param(rateValuesBlock, 'PortHandles');
feedforwardEnableHandles = get_param(feedforwardEnableBlock, 'PortHandles');

add_line(modelName, positionHandles.Outport, sourceHandles.Inport(1), 'autorouting', 'on');
add_line(modelName, rateHandles.Outport, sourceHandles.Inport(2), 'autorouting', 'on');
add_line(modelName, feedforwardEnableHandles.Outport, sourceHandles.Inport(3), 'autorouting', 'on');

referenceBlocks = struct( ...
    'SourceBlock', sourceBlock, ...
    'PositionReferencePort', 1, ...
    'RateReferencePort', 2, ...
    'PositionCommandPort', 1, ...
    'RateCommandPort', 2);
end

function localBuildReferenceSubsystem(sourceBlock)
lineHandles = find_system(sourceBlock, 'FindAll', 'on', 'Type', 'line');
if ~isempty(lineHandles)
    delete_line(lineHandles);
end

blocks = find_system(sourceBlock, 'SearchDepth', 1, 'Type', 'Block');
for k = 2:numel(blocks)
    delete_block(blocks{k});
end

add_block('simulink/Sources/In1', [sourceBlock '/position_values_6064'], ...
    'Position', [30 45 60 59]);
add_block('simulink/Sources/In1', [sourceBlock '/rate_values_6064'], ...
    'Position', [30 95 60 109]);
add_block('simulink/Sources/In1', [sourceBlock '/feedforward_enabled'], ...
    'Position', [30 145 60 159]);
add_block('simulink/Discrete/Unit Delay', [sourceBlock '/sample_index_delay'], ...
    'InitialCondition', '1', ...
    'SampleTime', '-1', ...
    'Position', [110 205 160 235]);
add_block('simulink/User-Defined Functions/MATLAB Function', [sourceBlock '/reference_step'], ...
    'Position', [220 65 440 205]);
add_block('simulink/Sinks/Out1', [sourceBlock '/position_reference_6064'], ...
    'Position', [520 70 550 84]);
add_block('simulink/Sinks/Out1', [sourceBlock '/position_rate_reference_6064'], ...
    'Position', [520 120 550 134]);
add_block('simulink/Sinks/Out1', [sourceBlock '/sample_index_next'], ...
    'Position', [520 205 550 219]);

block = [sourceBlock '/reference_step'];
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', block);
chart.Script = sprintf([ ...
    'function [position_ref, rate_ref, next_index] = reference_step(position_values, rate_values, feedforward_enabled, sample_index)\n' ...
    '%%#codegen\n' ...
    'count = numel(position_values);\n' ...
    'idx = round(sample_index);\n' ...
    'if idx < 1\n' ...
    '    idx = 1;\n' ...
    'end\n' ...
    'if idx > count\n' ...
    '    position_ref = int32(0);\n' ...
    '    raw_rate = int32(0);\n' ...
    'else\n' ...
    '    position_ref = int32(position_values(idx));\n' ...
    '    raw_rate = int32(rate_values(idx));\n' ...
    'end\n' ...
    'if int32(feedforward_enabled) ~= int32(0)\n' ...
    '    rate_ref = raw_rate;\n' ...
    'else\n' ...
    '    rate_ref = int32(0);\n' ...
    'end\n' ...
    'if idx < count\n' ...
    '    next_index = idx + 1;\n' ...
    'else\n' ...
    '    next_index = count + 1;\n' ...
    'end\n' ...
    'end\n']);

add_line(sourceBlock, 'position_values_6064/1', 'reference_step/1', 'autorouting', 'on');
add_line(sourceBlock, 'rate_values_6064/1', 'reference_step/2', 'autorouting', 'on');
add_line(sourceBlock, 'feedforward_enabled/1', 'reference_step/3', 'autorouting', 'on');
add_line(sourceBlock, 'sample_index_delay/1', 'reference_step/4', 'autorouting', 'on');
add_line(sourceBlock, 'reference_step/1', 'position_reference_6064/1', 'autorouting', 'on');
add_line(sourceBlock, 'reference_step/2', 'position_rate_reference_6064/1', 'autorouting', 'on');
add_line(sourceBlock, 'reference_step/3', 'sample_index_next/1', 'autorouting', 'on');
add_line(sourceBlock, 'reference_step/3', 'sample_index_delay/1', 'autorouting', 'on');
end
