function ids = autoStartStepIds()
ids = struct( ...
    'WAIT_BUS_OP', uint8(1), ...
    'WAIT_DRIVE_CLEAR', uint8(2), ...
    'AUTO_POWER_ON', uint8(3), ...
    'AUTO_ENABLE', uint8(4), ...
    'READY_TO_RUN', uint8(5));
end
