function buildStartupChart(target)
load_system('sflib');

subsystemPath = char(target);
chartBlock = [subsystemPath '/StartupChart'];

if getSimulinkBlockHandle([subsystemPath '/In1']) > 0
    delete_block([subsystemPath '/In1']);
end

if getSimulinkBlockHandle([subsystemPath '/Out1']) > 0
    delete_block([subsystemPath '/Out1']);
end

if getSimulinkBlockHandle(chartBlock) > 0
    delete_block(chartBlock);
end

add_block('sflib/Chart', chartBlock, 'Position', [250 70 520 360]);
chart = find(sfroot, '-isa', 'Stateflow.Chart', 'Path', chartBlock);
chart.ActionLanguage = "MATLAB";
chart.StateMachineType = "Classic";

inputSpecs = { ...
    'actual_network_state', 'int32', 1; ...
    'expected_network_state', 'int32', 2; ...
    'statusword_6041', 'uint16', 3; ...
    'error_code_603f', 'uint16', 4; ...
    'mode_display_6061', 'int8', 5; ...
    'velocity_actual_606c', 'int32', 6; ...
    'speed_command_60ff', 'int32', 7; ...
    'speed_limit_607f', 'uint32', 8};

outputSpecs = { ...
    'controlword_6040', 'uint16', 1; ...
    'velocity_command_60ff', 'int32', 2; ...
    'mode_command_6060', 'int8', 3; ...
    'speed_limit_out_607f', 'uint32', 4; ...
    'ready_to_run', 'uint8', 5; ...
    'auto_start_step', 'uint8', 6; ...
    'diag_code', 'uint8', 7; ...
    'diag_message_id', 'uint8', 8; ...
    'diag_lookup_group', 'uint8', 9; ...
    'diag_lookup_hint', 'uint8', 10};

for k = 1:size(inputSpecs, 1)
    inBlock = [subsystemPath '/' inputSpecs{k, 1}];
    add_block('simulink/Sources/In1', inBlock, ...
        'Port', num2str(inputSpecs{k, 3}), ...
        'Position', [35 30 + (k - 1) * 35 65 44 + (k - 1) * 35]);
end

for k = 1:size(outputSpecs, 1)
    outBlock = [subsystemPath '/' outputSpecs{k, 1}];
    add_block('simulink/Sinks/Out1', outBlock, ...
        'Port', num2str(outputSpecs{k, 3}), ...
        'Position', [735 30 + (k - 1) * 30 765 44 + (k - 1) * 30]);
end

configureData(chart, inputSpecs, outputSpecs);
addStartupBehavior(chart);

set_param(bdroot(subsystemPath), 'SimulationCommand', 'update');

chartHandles = get_param(chartBlock, 'PortHandles');
for k = 1:size(inputSpecs, 1)
    inHandles = get_param([subsystemPath '/' inputSpecs{k, 1}], 'PortHandles');
    add_line(subsystemPath, inHandles.Outport, chartHandles.Inport(inputSpecs{k, 3}), 'autorouting', 'on');
end

for k = 1:size(outputSpecs, 1)
    if outputSpecs{k, 3} == 10
        continue;
    end
    outHandles = get_param([subsystemPath '/' outputSpecs{k, 1}], 'PortHandles');
    add_line(subsystemPath, chartHandles.Outport(outputSpecs{k, 3}), outHandles.Inport, 'autorouting', 'on');
end

hintTerminator = [subsystemPath '/diag_lookup_hint_terminator'];
if getSimulinkBlockHandle(hintTerminator) > 0
    delete_block(hintTerminator);
end
add_block('simulink/Sinks/Terminator', hintTerminator, ...
    'Position', [640 360 670 390]);
add_line(subsystemPath, chartHandles.Outport(10), get_param(hintTerminator, 'PortHandles').Inport, 'autorouting', 'on');

addDiagLookupHintNetwork(subsystemPath, chartHandles);
end

function configureData(chart, inputSpecs, outputSpecs)
for k = 1:size(inputSpecs, 1)
    data = Stateflow.Data(chart);
    data.Name = inputSpecs{k, 1};
    data.Scope = "Input";
    data.Port = inputSpecs{k, 3};
    data.Props.Type.Method = "Built-in";
    data.DataType = inputSpecs{k, 2};
    data.Props.Array.Size = "1";
end

for k = 1:size(outputSpecs, 1)
    data = Stateflow.Data(chart);
    data.Name = outputSpecs{k, 1};
    data.Scope = "Output";
    data.Port = outputSpecs{k, 3};
    data.Props.Type.Method = "Built-in";
    data.DataType = outputSpecs{k, 2};
    if strcmp(outputSpecs{k, 1}, 'diag_lookup_hint')
        data.Props.Array.Size = "[1 48]";
        data.Props.InitialValue = "uint8(zeros(1,48))";
    else
        data.Props.Array.Size = "1";
    end
end
end

function addStartupBehavior(chart)
state = Stateflow.State(chart);
state.Name = "Run";
state.Position = [160 100 310 200];
state.LabelString = sprintf([ ...
    'Run\n' ...
    'during:\n' ...
    '    controlword_6040 = sgv2.controlword(''disable_voltage'');\n' ...
    '    velocity_command_60ff = int32(0);\n' ...
    '    mode_command_6060 = int8(9);\n' ...
    '    speed_limit_out_607f = speed_limit_607f;\n' ...
    '    ready_to_run = uint8(0);\n' ...
    '    auto_start_step = sgv2.internal.autoStartStepIds().WAIT_BUS_OP;\n' ...
    '    diag_code = sgv2.internal.diagCodes().NONE;\n' ...
    '    diag_message_id = sgv2.internal.diagMessageIds().NONE;\n' ...
    '    diag_lookup_group = sgv2.internal.diagLookupGroups().NONE;\n' ...
    '    diag_lookup_hint = uint8(zeros(1, 48));\n' ...
    '    if int32(actual_network_state) ~= int32(expected_network_state)\n' ...
    '        auto_start_step = sgv2.internal.autoStartStepIds().WAIT_BUS_OP;\n' ...
    '        diag_code = sgv2.internal.diagCodes().BUS_NOT_OP;\n' ...
    '        diag_message_id = sgv2.internal.diagMessageIds().CHECK_ETHERCAT_STATE;\n' ...
    '        diag_lookup_group = sgv2.internal.diagLookupGroups().ETHERCAT;\n' ...
    '    elseif uint16(error_code_603f) ~= uint16(0)\n' ...
    '        auto_start_step = sgv2.internal.autoStartStepIds().WAIT_DRIVE_CLEAR;\n' ...
    '        diag_code = sgv2.internal.diagCodes().DRIVE_ERROR;\n' ...
    '        diag_message_id = sgv2.internal.diagMessageIds().CHECK_603F;\n' ...
    '        diag_lookup_group = sgv2.internal.diagLookupGroups().ERROR_CODE_603F;\n' ...
    '    elseif sgv2.statusState(statusword_6041) >= sgv2.internal.faultStatusSentinel()\n' ...
    '        auto_start_step = sgv2.internal.autoStartStepIds().WAIT_DRIVE_CLEAR;\n' ...
    '        diag_code = sgv2.internal.diagCodes().DRIVE_FAULT;\n' ...
    '        diag_message_id = sgv2.internal.diagMessageIds().CHECK_6041;\n' ...
    '        diag_lookup_group = sgv2.internal.diagLookupGroups().STATUSWORD_6041;\n' ...
    '    elseif sgv2.statusState(statusword_6041) == uint8(1)\n' ...
    '        auto_start_step = sgv2.internal.autoStartStepIds().AUTO_POWER_ON;\n' ...
    '        controlword_6040 = sgv2.controlword(''shutdown'');\n' ...
    '    elseif sgv2.statusState(statusword_6041) == uint8(2)\n' ...
    '        auto_start_step = sgv2.internal.autoStartStepIds().AUTO_ENABLE;\n' ...
    '        controlword_6040 = sgv2.controlword(''switch_on'');\n' ...
    '    elseif sgv2.statusState(statusword_6041) == uint8(3)\n' ...
    '        auto_start_step = sgv2.internal.autoStartStepIds().AUTO_ENABLE;\n' ...
    '        controlword_6040 = sgv2.controlword(''enable_operation'');\n' ...
    '    elseif sgv2.statusState(statusword_6041) == uint8(4) && int8(mode_display_6061) ~= int8(9)\n' ...
    '        auto_start_step = sgv2.internal.autoStartStepIds().AUTO_ENABLE;\n' ...
    '        controlword_6040 = sgv2.controlword(''enable_operation'');\n' ...
    '        diag_code = sgv2.internal.diagCodes().MODE_MISMATCH;\n' ...
    '        diag_message_id = sgv2.internal.diagMessageIds().CHECK_6061;\n' ...
    '        diag_lookup_group = sgv2.internal.diagLookupGroups().MODE_DISPLAY_6061;\n' ...
    '    elseif sgv2.statusState(statusword_6041) == uint8(4)\n' ...
    '        auto_start_step = sgv2.internal.autoStartStepIds().READY_TO_RUN;\n' ...
    '        controlword_6040 = sgv2.controlword(''enable_operation'');\n' ...
    '        velocity_command_60ff = speed_command_60ff;\n' ...
    '        ready_to_run = uint8(1);\n' ...
    '    else\n' ...
    '        auto_start_step = sgv2.internal.autoStartStepIds().WAIT_DRIVE_CLEAR;\n' ...
    '        diag_code = sgv2.internal.diagCodes().WAITING_ENABLE;\n' ...
    '        diag_message_id = sgv2.internal.diagMessageIds().CHECK_6041;\n' ...
    '        diag_lookup_group = sgv2.internal.diagLookupGroups().STATUSWORD_6041;\n' ...
    '    end\n' ...
    '    diag_lookup_hint = uint8(zeros(1, 48));\n' ...
    '    if diag_message_id == sgv2.internal.diagMessageIds().NONE\n' ...
    '        diag_lookup_hint = uint8(zeros(1, 48));\n' ...
    '    end']);
defaultTransition = Stateflow.Transition(chart);
defaultTransition.Destination = state;
end

function addDiagLookupHintNetwork(subsystemPath, chartHandles)
scaleBlock = [subsystemPath '/diag_message_id_scale'];
add_block('simulink/Math Operations/Gain', scaleBlock, ...
    'Gain', '0.1', ...
    'Position', [340 300 400 330]);

biasBlock = [subsystemPath '/diag_message_id_bias'];
add_block('simulink/Math Operations/Bias', biasBlock, ...
    'Bias', '1', ...
    'Position', [430 300 490 330]);

convertBlock = [subsystemPath '/diag_message_id_to_uint8'];
add_block('simulink/Signal Attributes/Data Type Conversion', convertBlock, ...
    'OutDataTypeStr', 'uint8', ...
    'Position', [500 300 560 330]);

lookupSwitch = [subsystemPath '/diag_lookup_hint_switch'];
add_block('simulink/Signal Routing/Multiport Switch', lookupSwitch, ...
    'Inputs', '5', ...
    'DataPortOrder', 'One-based contiguous', ...
    'Position', [600 300 690 430]);

add_line(subsystemPath, chartHandles.Outport(8), get_param(scaleBlock, 'PortHandles').Inport, 'autorouting', 'on');
add_line(subsystemPath, get_param(scaleBlock, 'PortHandles').Outport, get_param(biasBlock, 'PortHandles').Inport, 'autorouting', 'on');
add_line(subsystemPath, get_param(biasBlock, 'PortHandles').Outport, get_param(convertBlock, 'PortHandles').Inport, 'autorouting', 'on');
add_line(subsystemPath, get_param(convertBlock, 'PortHandles').Outport, get_param(lookupSwitch, 'PortHandles').Inport(1), 'autorouting', 'on');

hintValues = localDiagLookupHintValues();
for k = 1:numel(hintValues)
    constantBlock = [subsystemPath '/diag_lookup_hint_' num2str(k)];
    add_block('simulink/Sources/Constant', constantBlock, ...
        'Value', hintValues{k}, ...
        'OutDataTypeStr', 'uint8', ...
        'Position', [90 300 + (k - 1) * 35 280 320 + (k - 1) * 35]);
    add_line(subsystemPath, get_param(constantBlock, 'PortHandles').Outport, get_param(lookupSwitch, 'PortHandles').Inport(k + 1), 'autorouting', 'on');
end

hintOutHandles = get_param([subsystemPath '/diag_lookup_hint'], 'PortHandles');
add_line(subsystemPath, get_param(lookupSwitch, 'PortHandles').Outport, hintOutHandles.Inport, 'autorouting', 'on');
end

function hintValues = localDiagLookupHintValues()
hintValues = { ...
    'uint8(zeros(1,48))', ...
    localHintExpr('Check EtherCAT manual: Get State / state machine'), ...
    localHintExpr('Check SV660N manual: 603Fh error code'), ...
    localHintExpr('Check SV660N manual: 6041h statusword / CiA402'), ...
    localHintExpr('Check SV660N manual: 6061h mode')};
end

function expr = localHintExpr(text)
padding = repmat(' ', 1, 48 - numel(text));
expr = sprintf('uint8(''%s%s'')', text, padding);
end
