function buildPositionLoopChart(target, targetConfig)
load_system('sflib');

subsystemPath = char(target);
chartBlock = [subsystemPath '/PositionLoopChart'];

if getSimulinkBlockHandle([subsystemPath '/In1']) > 0
    delete_block([subsystemPath '/In1']);
end

if getSimulinkBlockHandle([subsystemPath '/Out1']) > 0
    delete_block([subsystemPath '/Out1']);
end

if getSimulinkBlockHandle(chartBlock) > 0
    delete_block(chartBlock);
end

add_block('sflib/Chart', chartBlock, 'Position', [245 95 545 330]);
chart = find(sfroot, '-isa', 'Stateflow.Chart', 'Path', chartBlock);
chart.ActionLanguage = "MATLAB";
chart.StateMachineType = "Classic";

inputSpecs = { ...
    'position_command_6064', 'int32', 1, "Inport", ""; ...
    'position_rate_command_6064', 'int32', 2, "Inport", ""; ...
    'position_actual_6064', 'int32', 3, "Inport", ""; ...
    'ready_to_run', 'uint8', 4, "Inport", ""; ...
    'position_loop_enabled_request', 'int32', 5, "Inport", ""; ...
    'position_loop_kp', 'int32', 6, "Inport", ""; ...
    'position_loop_ki', 'int32', 7, "Inport", ""; ...
    'position_loop_kd', 'int32', 8, "Inport", ""; ...
    'position_loop_sample_time', 'double', 9, "Inport", ""; ...
    'position_loop_integrator_limit', 'int32', 10, "Inport", ""; ...
    'position_velocity_gain', 'int32', 11, "Inport", ""; ...
    'position_velocity_bias', 'int32', 12, "Inport", ""; ...
    'command_deadband', 'int32', 13, "Inport", ""; ...
    'max_tracking_speed', 'int32', 14, "Inport", ""};

outputSpecs = { ...
    'position_loop_speed_command_60ff', 'int32', 1; ...
    'position_error_6064', 'int32', 2; ...
    'position_ff_velocity_60ff', 'int32', 3; ...
    'position_pid_velocity_60ff', 'int32', 4; ...
    'position_loop_enabled', 'uint8', 5};

for k = 1:size(inputSpecs, 1)
    sourceBlockName = inputSpecs{k, 1};
    sourceType = inputSpecs{k, 4};
    if sourceType == "Constant"
        sourceBlockName = [sourceBlockName '_constant'];
    end

    inBlock = [subsystemPath '/' sourceBlockName];
    if getSimulinkBlockHandle(inBlock) > 0
        delete_block(inBlock);
    end
    if sourceType == "Inport"
        add_block('simulink/Sources/In1', inBlock, ...
            'Port', num2str(inputSpecs{k, 3}), ...
            'Position', [35 55 + (k - 1) * 45 65 69 + (k - 1) * 45]);
    else
        add_block('simulink/Sources/Constant', inBlock, ...
            'Value', inputSpecs{k, 5}, ...
            'OutDataTypeStr', inputSpecs{k, 2}, ...
            'Position', [35 55 + (k - 1) * 45 95 69 + (k - 1) * 45]);
    end
end

for k = 1:size(outputSpecs, 1)
    outBlock = [subsystemPath '/' outputSpecs{k, 1}];
    add_block('simulink/Sinks/Out1', outBlock, ...
        'Port', num2str(outputSpecs{k, 3}), ...
        'Position', [725 55 + (k - 1) * 45 755 69 + (k - 1) * 45]);
end

configureData(chart, inputSpecs, outputSpecs);
addPositionLoopBehavior(chart);

chartHandles = get_param(chartBlock, 'PortHandles');
for k = 1:size(inputSpecs, 1)
    sourceBlockName = inputSpecs{k, 1};
    if inputSpecs{k, 4} == "Constant"
        sourceBlockName = [sourceBlockName '_constant'];
    end
    inHandles = get_param([subsystemPath '/' sourceBlockName], 'PortHandles');
    add_line(subsystemPath, inHandles.Outport, chartHandles.Inport(inputSpecs{k, 3}), 'autorouting', 'on');
end

for k = 1:size(outputSpecs, 1)
    outHandles = get_param([subsystemPath '/' outputSpecs{k, 1}], 'PortHandles');
    add_line(subsystemPath, chartHandles.Outport(outputSpecs{k, 3}), outHandles.Inport, 'autorouting', 'on');
end
end

function configureData(chart, inputSpecs, outputSpecs)
for k = 1:size(inputSpecs, 1)
    data = Stateflow.Data(chart);
    data.Name = inputSpecs{k, 1};
    data.Scope = "Input";
    data.Port = inputSpecs{k, 3};
    data.Props.Type.Method = "Built-in";
    data.DataType = inputSpecs{k, 2};
    data.Props.Array.Size = "1";
end

for k = 1:size(outputSpecs, 1)
    data = Stateflow.Data(chart);
    data.Name = outputSpecs{k, 1};
    data.Scope = "Output";
    data.Port = outputSpecs{k, 3};
    data.Props.Type.Method = "Built-in";
    data.DataType = outputSpecs{k, 2};
    data.Props.Array.Size = "1";
end

localSpecs = { ...
    'integral_6064'; ...
    'previous_error_6064'; ...
    'rawFeedforward60FF'; ...
    'error6064'; ...
    'derivative6064'; ...
    'rawPidVelocity60FF'; ...
    'rawSpeedCommand60FF'; ...
    'maxTrackingSpeed60FF'; ...
    'kpGain'; ...
    'kiGain'; ...
    'kdGain'};
for k = 1:numel(localSpecs)
    data = Stateflow.Data(chart);
    data.Name = localSpecs{k};
    data.Scope = "Local";
    data.Props.Type.Method = "Built-in";
    data.DataType = "double";
    data.Props.Array.Size = "1";
    data.Props.InitialValue = "0";
end
end

function addPositionLoopBehavior(chart)
state = Stateflow.State(chart);
state.Name = "Run";
state.Position = [165 100 345 205];
state.LabelString = sprintf([ ...
    'Run\n' ...
    'during:\n' ...
    '    position_loop_speed_command_60ff = int32(0);\n' ...
    '    position_error_6064 = int32(0);\n' ...
    '    position_ff_velocity_60ff = int32(0);\n' ...
    '    position_pid_velocity_60ff = int32(0);\n' ...
    '    position_loop_enabled = uint8(0);\n' ...
    '    if sgv2.control.computePositionLoopGate(ready_to_run, uint8(position_loop_enabled_request ~= int32(0)))\n' ...
    '        position_loop_enabled = uint8(1);\n' ...
    '        position_error_6064 = int32(position_command_6064) - int32(position_actual_6064);\n' ...
    '        rawFeedforward60FF = (double(position_rate_command_6064) - double(position_velocity_bias)) / max(double(position_velocity_gain), 1);\n' ...
    '        if abs(rawFeedforward60FF) <= double(command_deadband)\n' ...
    '            rawFeedforward60FF = 0;\n' ...
    '        end\n' ...
    '        maxTrackingSpeed60FF = double(max_tracking_speed);\n' ...
    '        rawFeedforward60FF = min(max(rawFeedforward60FF, -maxTrackingSpeed60FF), maxTrackingSpeed60FF);\n' ...
    '        position_ff_velocity_60ff = int32(round(rawFeedforward60FF));\n' ...
    '        error6064 = double(position_error_6064);\n' ...
    '        kpGain = double(position_loop_kp) * 0.001;\n' ...
    '        kiGain = double(position_loop_ki) * 0.001;\n' ...
    '        kdGain = double(position_loop_kd) * 0.001;\n' ...
    '        integral_6064 = integral_6064 + kiGain * error6064 * position_loop_sample_time;\n' ...
    '        integral_6064 = min(max(integral_6064, -double(position_loop_integrator_limit)), double(position_loop_integrator_limit));\n' ...
    '        derivative6064 = (error6064 - previous_error_6064) / position_loop_sample_time;\n' ...
    '        rawPidVelocity60FF = kpGain * error6064 + integral_6064 + kdGain * derivative6064;\n' ...
    '        position_pid_velocity_60ff = int32(round(rawPidVelocity60FF));\n' ...
    '        rawSpeedCommand60FF = rawFeedforward60FF + rawPidVelocity60FF;\n' ...
    '        rawSpeedCommand60FF = min(max(rawSpeedCommand60FF, -maxTrackingSpeed60FF), maxTrackingSpeed60FF);\n' ...
    '        position_loop_speed_command_60ff = int32(round(rawSpeedCommand60FF));\n' ...
    '        previous_error_6064 = error6064;\n' ...
    '    else\n' ...
        '        integral_6064 = 0;\n' ...
        '        previous_error_6064 = 0;\n' ...
    '    end']);
defaultTransition = Stateflow.Transition(chart);
defaultTransition.Destination = state;
end
