function modelName = buildFrameworkHarness()
defaults = project_defaults();
target = target_minimal_slrtexplorer();
modelName = char(defaults.HarnessModelName);

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

load_system('simulink');
load_system('sflib');

new_system(modelName);
set_param(modelName, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(defaults.SampleTime), ...
    'StopTime', '0.05', ...
    'SignalLogging', 'on', ...
    'SignalLoggingName', 'logsout');

controllerBlock = [modelName '/SV660N Sequence Controller'];
add_block('simulink/Ports & Subsystems/Subsystem', controllerBlock, ...
    'Position', [320 80 700 420]);
sgv2.internal.buildStartupChart(controllerBlock);
controllerHandles = get_param(controllerBlock, 'PortHandles');

items = { ...
    'actual_network_state', 'network_state_ts', [30 60 140 80], 1; ...
    'expected_network_state', ['timeseries(int32([' num2str(target.Ethercat.ExpectedNetworkState) ' ' num2str(target.Ethercat.ExpectedNetworkState) ']), [0 0.05])'], [30 100 140 120], 2; ...
    'statusword_6041', 'statusword_ts', [30 140 140 160], 3; ...
    'error_code_603f', 'error_code_ts', [30 180 140 200], 4; ...
    'mode_display_6061', 'mode_display_ts', [30 220 140 240], 5; ...
    'velocity_actual_606c', 'velocity_actual_ts', [30 260 140 280], 6; ...
    'speed_command_60ff', 'speed_command_ts', [30 300 140 320], 7; ...
    'speed_limit_607f', 'speed_limit_ts', [30 340 140 360], 8};

for k = 1:size(items, 1)
    sourceBlock = [modelName '/' items{k, 1}];
    add_block('simulink/Sources/From Workspace', sourceBlock, ...
        'Position', items{k, 3}, ...
        'VariableName', items{k, 2});
    sourceHandles = get_param(sourceBlock, 'PortHandles');
    add_line(modelName, sourceHandles.Outport, controllerHandles.Inport(items{k, 4}), 'autorouting', 'on');
end

loggedOutputs = { ...
    'controlword_6040', 1; ...
    'velocity_command_60ff', 2; ...
    'ready_to_run', 5; ...
    'auto_start_step', 6; ...
    'diag_code', 7; ...
    'diag_message_id', 8; ...
    'diag_lookup_group', 9; ...
    'diag_lookup_hint', 10};
for k = 1:size(loggedOutputs, 1)
    outBlock = [modelName '/' loggedOutputs{k, 1}];
    add_block('simulink/Sinks/Out1', outBlock, ...
        'Position', [770 100 + (k - 1) * 45 800 114 + (k - 1) * 45]);
    outHandles = get_param(outBlock, 'PortHandles');
    lineHandle = add_line(modelName, controllerHandles.Outport(loggedOutputs{k, 2}), outHandles.Inport, 'autorouting', 'on');
    set_param(lineHandle, 'Name', loggedOutputs{k, 1});
    Simulink.sdi.markSignalForStreaming(lineHandle, 'on');
end

terminatedOutputs = { ...
    'mode_command_6060', 3; ...
    'speed_limit_out_607f', 4};
for k = 1:size(terminatedOutputs, 1)
    terminatorBlock = [modelName '/' terminatedOutputs{k, 1} '_terminator'];
    add_block('simulink/Sinks/Terminator', terminatorBlock, ...
        'Position', [770 465 + (k - 1) * 45 800 495 + (k - 1) * 45]);
    terminatorHandles = get_param(terminatorBlock, 'PortHandles');
    add_line(modelName, controllerHandles.Outport(terminatedOutputs{k, 2}), ...
        terminatorHandles.Inport, 'autorouting', 'on');
end
end
