function buildStartupChart(target)
load_system('simulink');

subsystemPath = char(target);
localClearSubsystem(subsystemPath);

inputSpecs = { ...
    'actual_network_state', 1; ...
    'expected_network_state', 2; ...
    'statusword_6041', 3; ...
    'error_code_603f', 4; ...
    'mode_display_6061', 5; ...
    'velocity_actual_606c', 6; ...
    'speed_command_60ff', 7; ...
    'speed_limit_607f', 8};

outputSpecs = { ...
    'controlword_6040', 1; ...
    'velocity_command_60ff', 2; ...
    'mode_command_6060', 3; ...
    'speed_limit_out_607f', 4; ...
    'ready_to_run', 5; ...
    'auto_start_step', 6; ...
    'diag_code', 7; ...
    'diag_message_id', 8; ...
    'diag_lookup_group', 9; ...
    'diag_lookup_hint', 10};

for k = 1:size(inputSpecs, 1)
    add_block('simulink/Sources/In1', [subsystemPath '/' inputSpecs{k, 1}], ...
        'Port', num2str(inputSpecs{k, 2}), ...
        'Position', [35 30 + (k - 1) * 45 65 44 + (k - 1) * 45]);
end

for k = 1:size(outputSpecs, 1)
    add_block('simulink/Sinks/Out1', [subsystemPath '/' outputSpecs{k, 1}], ...
        'Port', num2str(outputSpecs{k, 2}), ...
        'Position', [800 30 + (k - 1) * 40 830 44 + (k - 1) * 40]);
end

decisionBlock = [subsystemPath '/startup_decision'];
add_block('simulink/User-Defined Functions/MATLAB Function', decisionBlock, ...
    'Position', [260 95 470 265]);
localSetMatlabFunctionScript(decisionBlock, localStartupDecisionScript());

zeroVelocityBlock = [subsystemPath '/zero_velocity_command_60ff'];
add_block('simulink/Sources/Constant', zeroVelocityBlock, ...
    'Value', 'int32(0)', ...
    'OutDataTypeStr', 'int32', ...
    'Position', [520 105 580 125]);

velocitySwitchBlock = [subsystemPath '/velocity_command_ready_switch'];
add_block('simulink/Signal Routing/Switch', velocitySwitchBlock, ...
    'Criteria', 'u2 ~= 0', ...
    'Position', [625 80 685 140]);

modeCommandBlock = [subsystemPath '/mode_command_csv'];
add_block('simulink/Sources/Constant', modeCommandBlock, ...
    'Value', 'int8(9)', ...
    'OutDataTypeStr', 'int8', ...
    'Position', [625 150 685 175]);

unusedVelocityTerminator = [subsystemPath '/velocity_actual_606c_terminator'];
add_block('simulink/Sinks/Terminator', unusedVelocityTerminator, ...
    'Position', [250 285 280 315]);

inputHandles = localBlockHandles(subsystemPath, inputSpecs(:, 1));
outputHandles = localBlockHandles(subsystemPath, outputSpecs(:, 1));
decisionHandles = get_param(decisionBlock, 'PortHandles');
zeroVelocityHandles = get_param(zeroVelocityBlock, 'PortHandles');
velocitySwitchHandles = get_param(velocitySwitchBlock, 'PortHandles');
modeCommandHandles = get_param(modeCommandBlock, 'PortHandles');
unusedVelocityHandles = get_param(unusedVelocityTerminator, 'PortHandles');

for k = 1:5
    add_line(subsystemPath, inputHandles{k}.Outport, decisionHandles.Inport(k), 'autorouting', 'on');
end
add_line(subsystemPath, inputHandles{6}.Outport, unusedVelocityHandles.Inport, 'autorouting', 'on');

add_line(subsystemPath, inputHandles{7}.Outport, velocitySwitchHandles.Inport(1), 'autorouting', 'on');
add_line(subsystemPath, decisionHandles.Outport(2), velocitySwitchHandles.Inport(2), 'autorouting', 'on');
add_line(subsystemPath, zeroVelocityHandles.Outport, velocitySwitchHandles.Inport(3), 'autorouting', 'on');

add_line(subsystemPath, decisionHandles.Outport(1), outputHandles{1}.Inport, 'autorouting', 'on');
add_line(subsystemPath, velocitySwitchHandles.Outport, outputHandles{2}.Inport, 'autorouting', 'on');
add_line(subsystemPath, modeCommandHandles.Outport, outputHandles{3}.Inport, 'autorouting', 'on');
add_line(subsystemPath, inputHandles{8}.Outport, outputHandles{4}.Inport, 'autorouting', 'on');
add_line(subsystemPath, decisionHandles.Outport(2), outputHandles{5}.Inport, 'autorouting', 'on');
add_line(subsystemPath, decisionHandles.Outport(3), outputHandles{6}.Inport, 'autorouting', 'on');
add_line(subsystemPath, decisionHandles.Outport(4), outputHandles{7}.Inport, 'autorouting', 'on');
add_line(subsystemPath, decisionHandles.Outport(5), outputHandles{8}.Inport, 'autorouting', 'on');
add_line(subsystemPath, decisionHandles.Outport(6), outputHandles{9}.Inport, 'autorouting', 'on');

addDiagLookupHintNetwork(subsystemPath, decisionHandles.Outport(5), outputHandles{10}.Inport);
end

function localClearSubsystem(subsystemPath)
lines = find_system(subsystemPath, 'FindAll', 'on', 'SearchDepth', 1, 'Type', 'line');
for k = numel(lines):-1:1
    delete_line(lines(k));
end

blocks = find_system(subsystemPath, 'SearchDepth', 1, 'Type', 'Block');
for k = numel(blocks):-1:1
    if ~strcmp(blocks{k}, subsystemPath)
        delete_block(blocks{k});
    end
end
end

function handles = localBlockHandles(subsystemPath, names)
handles = cell(numel(names), 1);
for k = 1:numel(names)
    handles{k} = get_param([subsystemPath '/' names{k}], 'PortHandles');
end
end

function localSetMatlabFunctionScript(blockPath, scriptText)
root = sfroot;
chart = root.find('-isa', 'Stateflow.EMChart', 'Path', blockPath);
if isempty(chart)
    error('sgv2:MatlabFunctionBlockNotFound', ...
        'Could not find MATLAB Function block at %s.', blockPath);
end
chart(1).Script = scriptText;
end

function scriptText = localStartupDecisionScript()
scriptText = sprintf([ ...
    'function [controlword_6040, ready_to_run, auto_start_step, diag_code, diag_message_id, diag_lookup_group] = startup_decision(actual_network_state, expected_network_state, statusword_6041, error_code_603f, mode_display_6061)\n' ...
    'controlword_6040 = sgv2.controlword(''disable_voltage'');\n' ...
    'ready_to_run = uint8(0);\n' ...
    'auto_start_step = sgv2.internal.autoStartStepIds().WAIT_BUS_OP;\n' ...
    'diag_code = sgv2.internal.diagCodes().NONE;\n' ...
    'diag_message_id = sgv2.internal.diagMessageIds().NONE;\n' ...
    'diag_lookup_group = sgv2.internal.diagLookupGroups().NONE;\n' ...
    'status_state = sgv2.statusState(statusword_6041);\n' ...
    'if int32(actual_network_state) ~= int32(expected_network_state)\n' ...
    '    auto_start_step = sgv2.internal.autoStartStepIds().WAIT_BUS_OP;\n' ...
    '    diag_code = sgv2.internal.diagCodes().BUS_NOT_OP;\n' ...
    '    diag_message_id = sgv2.internal.diagMessageIds().CHECK_ETHERCAT_STATE;\n' ...
    '    diag_lookup_group = sgv2.internal.diagLookupGroups().ETHERCAT;\n' ...
    'elseif uint16(error_code_603f) ~= uint16(0)\n' ...
    '    auto_start_step = sgv2.internal.autoStartStepIds().WAIT_DRIVE_CLEAR;\n' ...
    '    diag_code = sgv2.internal.diagCodes().DRIVE_ERROR;\n' ...
    '    diag_message_id = sgv2.internal.diagMessageIds().CHECK_603F;\n' ...
    '    diag_lookup_group = sgv2.internal.diagLookupGroups().ERROR_CODE_603F;\n' ...
    'elseif status_state >= sgv2.internal.faultStatusSentinel()\n' ...
    '    auto_start_step = sgv2.internal.autoStartStepIds().WAIT_DRIVE_CLEAR;\n' ...
    '    diag_code = sgv2.internal.diagCodes().DRIVE_FAULT;\n' ...
    '    diag_message_id = sgv2.internal.diagMessageIds().CHECK_6041;\n' ...
    '    diag_lookup_group = sgv2.internal.diagLookupGroups().STATUSWORD_6041;\n' ...
    'elseif status_state == uint8(1)\n' ...
    '    auto_start_step = sgv2.internal.autoStartStepIds().AUTO_POWER_ON;\n' ...
    '    controlword_6040 = sgv2.controlword(''shutdown'');\n' ...
    'elseif status_state == uint8(2)\n' ...
    '    auto_start_step = sgv2.internal.autoStartStepIds().AUTO_ENABLE;\n' ...
    '    controlword_6040 = sgv2.controlword(''switch_on'');\n' ...
    'elseif status_state == uint8(3)\n' ...
    '    auto_start_step = sgv2.internal.autoStartStepIds().AUTO_ENABLE;\n' ...
    '    controlword_6040 = sgv2.controlword(''enable_operation'');\n' ...
    'elseif status_state == uint8(4) && int8(mode_display_6061) ~= int8(9)\n' ...
    '    auto_start_step = sgv2.internal.autoStartStepIds().AUTO_ENABLE;\n' ...
    '    controlword_6040 = sgv2.controlword(''enable_operation'');\n' ...
    '    diag_code = sgv2.internal.diagCodes().MODE_MISMATCH;\n' ...
    '    diag_message_id = sgv2.internal.diagMessageIds().CHECK_6061;\n' ...
    '    diag_lookup_group = sgv2.internal.diagLookupGroups().MODE_DISPLAY_6061;\n' ...
    'elseif status_state == uint8(4)\n' ...
    '    auto_start_step = sgv2.internal.autoStartStepIds().READY_TO_RUN;\n' ...
    '    controlword_6040 = sgv2.controlword(''enable_operation'');\n' ...
    '    ready_to_run = uint8(1);\n' ...
    'else\n' ...
    '    auto_start_step = sgv2.internal.autoStartStepIds().WAIT_DRIVE_CLEAR;\n' ...
    '    diag_code = sgv2.internal.diagCodes().WAITING_ENABLE;\n' ...
    '    diag_message_id = sgv2.internal.diagMessageIds().CHECK_6041;\n' ...
    '    diag_lookup_group = sgv2.internal.diagLookupGroups().STATUSWORD_6041;\n' ...
    'end\n' ...
    'end\n']);
end

function addDiagLookupHintNetwork(subsystemPath, diagMessageSourcePort, diagLookupHintInport)
doubleBlock = [subsystemPath '/diag_message_id_to_double'];
add_block('simulink/Signal Attributes/Data Type Conversion', doubleBlock, ...
    'OutDataTypeStr', 'double', ...
    'Position', [500 300 560 330]);

scaleBlock = [subsystemPath '/diag_message_id_scale'];
add_block('simulink/Math Operations/Gain', scaleBlock, ...
    'Gain', '0.1', ...
    'Position', [580 300 640 330]);

biasBlock = [subsystemPath '/diag_message_id_bias'];
add_block('simulink/Math Operations/Bias', biasBlock, ...
    'Bias', '1', ...
    'Position', [660 300 720 330]);

convertBlock = [subsystemPath '/diag_message_id_to_uint8'];
add_block('simulink/Signal Attributes/Data Type Conversion', convertBlock, ...
    'OutDataTypeStr', 'uint8', ...
    'Position', [740 300 800 330]);

lookupSwitch = [subsystemPath '/diag_lookup_hint_switch'];
add_block('simulink/Signal Routing/Multiport Switch', lookupSwitch, ...
    'Inputs', '5', ...
    'DataPortOrder', 'One-based contiguous', ...
    'Position', [825 290 870 470]);

add_line(subsystemPath, diagMessageSourcePort, get_param(doubleBlock, 'PortHandles').Inport, 'autorouting', 'on');
add_line(subsystemPath, get_param(doubleBlock, 'PortHandles').Outport, get_param(scaleBlock, 'PortHandles').Inport, 'autorouting', 'on');
add_line(subsystemPath, get_param(scaleBlock, 'PortHandles').Outport, get_param(biasBlock, 'PortHandles').Inport, 'autorouting', 'on');
add_line(subsystemPath, get_param(biasBlock, 'PortHandles').Outport, get_param(convertBlock, 'PortHandles').Inport, 'autorouting', 'on');
add_line(subsystemPath, get_param(convertBlock, 'PortHandles').Outport, get_param(lookupSwitch, 'PortHandles').Inport(1), 'autorouting', 'on');

hintValues = localDiagLookupHintValues();
for k = 1:numel(hintValues)
    constantBlock = [subsystemPath '/diag_lookup_hint_' num2str(k)];
    add_block('simulink/Sources/Constant', constantBlock, ...
        'Value', hintValues{k}, ...
        'OutDataTypeStr', 'uint8', ...
        'Position', [500 350 + (k - 1) * 35 785 370 + (k - 1) * 35]);
    add_line(subsystemPath, get_param(constantBlock, 'PortHandles').Outport, get_param(lookupSwitch, 'PortHandles').Inport(k + 1), 'autorouting', 'on');
end

add_line(subsystemPath, get_param(lookupSwitch, 'PortHandles').Outport, diagLookupHintInport, 'autorouting', 'on');
end

function hintValues = localDiagLookupHintValues()
hintValues = { ...
    'uint8(zeros(1,48))', ...
    localHintExpr('Check EtherCAT manual: Get State / state machine'), ...
    localHintExpr('Check SV660N manual: 603Fh error code'), ...
    localHintExpr('Check SV660N manual: 6041h statusword / CiA402'), ...
    localHintExpr('Check SV660N manual: 6061h mode')};
end

function expr = localHintExpr(text)
padding = repmat(' ', 1, 48 - numel(text));
expr = sprintf('uint8(''%s%s'')', text, padding);
end
