function codes = diagCodes()
codes = struct( ...
    'NONE', uint8(0), ...
    'BUS_NOT_OP', uint8(1), ...
    'DRIVE_ERROR', uint8(2), ...
    'DRIVE_FAULT', uint8(3), ...
    'MODE_MISMATCH', uint8(4), ...
    'WAITING_ENABLE', uint8(5));
end
