function groups = diagLookupGroups()
groups = struct( ...
    'NONE', uint8(0), ...
    'ETHERCAT', uint8(1), ...
    'ERROR_CODE_603F', uint8(2), ...
    'STATUSWORD_6041', uint8(3), ...
    'MODE_DISPLAY_6061', uint8(4));
end
