function tests = test_positionLoop
tests = functiontests(localfunctions);
end

function testExternalTrajectoryInputCombinesFeedforwardAndPositionError(testCase)
params = struct( ...
    'PositionLoopEnabled', true, ...
    'PositionLoopKp', 0.5, ...
    'PositionLoopKi', 0.0, ...
    'PositionLoopKd', 0.0, ...
    'PositionLoopSampleTime', 0.002, ...
    'PositionLoopIntegratorLimit', 1000.0, ...
    'PositionVelocityGain', 1.0, ...
    'PositionVelocityBias', 0.0, ...
    'CommandDeadband', 0.0, ...
    'MaxTrackingSpeed', 6000.0);
state = struct( ...
    'Integral6064', 0.0, ...
    'PreviousError6064', 0.0);

result = sgv2.control.computePositionLoopCommand(int32(100), int32(50), int32(90), params, state);

verifyTrue(testCase, result.ModelValid);
verifyTrue(testCase, result.Enabled);
verifyEqual(testCase, result.PositionError6064, int32(10));
verifyEqual(testCase, result.PositionFeedforwardVelocity60FF, int32(50));
verifyEqual(testCase, result.PositionPidVelocity60FF, int32(5));
verifyEqual(testCase, result.SpeedCommand60FF, int32(55));
verifyEqual(testCase, result.FallbackReason, "");
end
