function defaults = project_defaults()
configDir = fileparts(mfilename('fullpath'));
matlabRoot = fileparts(configDir);
projectRoot = fileparts(matlabRoot);

defaults = struct( ...
    'ProjectName', "speedgoat_v2.0.0", ...
    'ProjectRoot', string(projectRoot), ...
    'MatlabRoot', string(matlabRoot), ...
    'ConfigRoot', string(configDir), ...
    'ModelRoot', string(fullfile(matlabRoot, 'model')), ...
    'ModelDir', string(fullfile(matlabRoot, 'model', 'models')), ...
    'DocsRoot', string(fullfile(projectRoot, 'docs')), ...
    'CommandPrefix', "SGV2", ...
    'DefaultModelName', "speedgoat_v2_minimal", ...
    'DefaultApplicationName', "speedgoat_v2_minimal", ...
    'HarnessModelName', "speedgoat_v2_sequence_harness", ...
    'SampleTime', 0.002);
end
