function target = target_minimal_slrtexplorer()
defaults = project_defaults();
axisCfg = sv660n_axis1();
ethercatCfg = sv660n_eni_contract(axisCfg, defaults.SampleTime, defaults.ConfigRoot);
pdoMap = sv660n_pdo_map();

target = struct( ...
    'TargetName', "Minimal slrtExplorer", ...
    'ModelName', defaults.DefaultModelName, ...
    'ApplicationName', defaults.DefaultApplicationName, ...
    'GeneratedModelFile', fullfile(defaults.ModelDir, defaults.DefaultModelName + ".slx"), ...
    'EniFile', ethercatCfg.EniFile, ...
    'SampleTime', defaults.SampleTime, ...
    'AxisConfig', axisCfg, ...
    'Ethercat', ethercatCfg, ...
    'PdoMap', pdoMap, ...
    'Tunables', struct( ...
        'SpeedCommand60FF', "SGV2_SPEED_COMMAND_60FF", ...
        'SpeedLimit607F', "SGV2_SPEED_LIMIT_607F", ...
        'IdentificationMaxSpeed60FF', "SGV2_IDENTIFICATION_MAX_SPEED_60FF", ...
        'IdentificationMaxTravel6064', "SGV2_IDENTIFICATION_MAX_TRAVEL_6064", ...
        'IdentificationStep6064', "SGV2_IDENTIFICATION_STEP_6064", ...
        'IdentificationStopBand6064', "SGV2_IDENTIFICATION_STOP_BAND_6064", ...
        'PositionReferenceFeedforwardEnabled', "SGV2_POSITION_REFERENCE_FEEDFORWARD_ENABLED", ...
        'ReferencePlayRequest', "SGV2_REFERENCE_PLAY_REQUEST", ...
        'HomeToZeroRequest', "SGV2_HOME_TO_ZERO_REQUEST", ...
        'HomeToZeroSpeed', "SGV2_HOME_TO_ZERO_SPEED", ...
        'PositionCommand6064', "SGV2_POSITION_COMMAND_6064", ...
        'PositionRateCommand6064', "SGV2_POSITION_RATE_COMMAND_6064", ...
        'PositionVelocityGain', "SGV2_POSITION_VELOCITY_GAIN", ...
        'PositionVelocityBias', "SGV2_POSITION_VELOCITY_BIAS", ...
        'CommandDeadband', "SGV2_COMMAND_DEADBAND", ...
        'CommandDelaySamples', "SGV2_COMMAND_DELAY_SAMPLES", ...
        'MaxTrackingSpeed', "SGV2_MAX_TRACKING_SPEED", ...
        'PositionUnitMillimetersPerCount6064', "SGV2_POSITION_UNIT_MILLIMETERS_PER_COUNT_6064", ...
        'PositionLoopKp', "SGV2_POSITION_LOOP_KP", ...
        'PositionLoopKi', "SGV2_POSITION_LOOP_KI", ...
        'PositionLoopKd', "SGV2_POSITION_LOOP_KD", ...
        'PositionLoopSampleTime', "SGV2_POSITION_LOOP_SAMPLE_TIME", ...
        'PositionLoopIntegratorLimit', "SGV2_POSITION_LOOP_INTEGRATOR_LIMIT"), ...
    'Signals', struct( ...
        'ActualNetworkState', "actual_network_state", ...
        'ExpectedNetworkState', "expected_network_state", ...
        'Statusword6041', "statusword_6041", ...
        'ErrorCode603F', "error_code_603f", ...
        'PositionActual6064', "position_actual_6064", ...
        'ModeDisplay6061', "mode_display_6061", ...
        'VelocityActual606C', "velocity_actual_606c", ...
        'DiagCode', "diag_code", ...
        'DiagMessageId', "diag_message_id", ...
        'DiagLookupGroup', "diag_lookup_group", ...
        'DiagLookupHint', "diag_lookup_hint", ...
        'ReadyToRun', "ready_to_run", ...
        'AutoStartStep', "auto_start_step", ...
        'PositionReference6064', "position_reference_6064", ...
        'PositionRateReference6064', "position_rate_reference_6064", ...
        'PositionCommand6064', "position_command_6064", ...
        'PositionRateCommand6064', "position_rate_command_6064", ...
        'PositionError6064', "position_error_6064", ...
        'PositionFeedforwardVelocity60FF', "position_ff_velocity_60ff", ...
        'PositionPidVelocity60FF', "position_pid_velocity_60ff", ...
        'PositionLoopSpeedCommand60FF', "position_loop_speed_command_60ff", ...
        'PositionLoopEnabled', "position_loop_enabled", ...
        'SpeedCommand60FF', "speed_command_60ff", ...
        'SpeedLimit607F', "speed_limit_607f"));
end
