function target = target_minimal_slrtexplorer()
defaults = project_defaults();
axisCfg = sv660n_axis1();
ethercatCfg = sv660n_eni_contract(axisCfg, defaults.SampleTime, defaults.ConfigRoot);
pdoMap = sv660n_pdo_map();

target = struct( ...
    'TargetName', "Minimal slrtExplorer", ...
    'ModelName', defaults.DefaultModelName, ...
    'ApplicationName', defaults.DefaultApplicationName, ...
    'GeneratedModelFile', fullfile(defaults.ModelDir, defaults.DefaultModelName + ".slx"), ...
    'EniFile', ethercatCfg.EniFile, ...
    'SampleTime', defaults.SampleTime, ...
    'AxisConfig', axisCfg, ...
    'Ethercat', ethercatCfg, ...
    'PdoMap', pdoMap, ...
    'Tunables', struct( ...
        'SpeedCommand60FF', "SGV2_SPEED_COMMAND_60FF", ...
        'SpeedLimit607F', "SGV2_SPEED_LIMIT_607F"), ...
    'Signals', struct( ...
        'ActualNetworkState', "actual_network_state", ...
        'ExpectedNetworkState', "expected_network_state", ...
        'Statusword6041', "statusword_6041", ...
        'ErrorCode603F', "error_code_603f", ...
        'PositionActual6064', "position_actual_6064", ...
        'ModeDisplay6061', "mode_display_6061", ...
        'VelocityActual606C', "velocity_actual_606c", ...
        'DiagCode', "diag_code", ...
        'DiagMessageId', "diag_message_id", ...
        'DiagLookupGroup', "diag_lookup_group", ...
        'DiagLookupHint', "diag_lookup_hint", ...
        'ReadyToRun', "ready_to_run", ...
        'AutoStartStep', "auto_start_step", ...
        'SpeedCommand60FF', "speed_command_60ff", ...
        'SpeedLimit607F', "speed_limit_607f"));
end
