function ethercatCfg = sv660n_eni_contract(axisCfg, sampleTime, configRoot)
ethercatCfg = struct( ...
    'EniFile', string(fullfile(configRoot, 'ethercat', 'eni', 'ENI2.xml')), ...
    'DeviceIndex', axisCfg.EthercatDeviceIndex, ...
    'PortNumber', axisCfg.EthernetPortNumber, ...
    'InitStateValue', "2", ...
    'ExpectedNetworkState', int32(8), ...
    'EnableDC', true, ...
    'DCModeValue', "2", ...
    'DCTuningValue', "0", ...
    'ExpectedModeOfOperation', axisCfg.ExpectedModeOfOperation, ...
    'SampleTime', sampleTime);
end
