function pdoMap = sv660n_pdo_map()
% Minimal first-version contract for the approved 1702h Outputs + 1B04h Inputs PDOs.
% This intentionally exposes only the Task 1 surface instead of mirroring every ENI object.
slave = "Drive 1 (InoSV660N)";
pdoMap = struct( ...
    'Rx', [ ...
        localPdo("errorCode603F", "Rx Error code 603F", slave + ".Inputs.Error code", 568, "uint16", 16) ...
        localPdo("statusword6041", "Rx Statusword 6041", slave + ".Inputs.Statusword", 584, "uint16", 16) ...
        localPdo("modeDisplay6061", "Rx Mode display 6061", slave + ".Inputs.Modes of operation display", 648, "int8", 8) ...
        localPdo("velocityActual606C", "Rx Velocity actual 606C", slave + ".Inputs.Velocity actual value", 768, "int32", 32)], ...
    'Tx', [ ...
        localPdo("controlword6040", "Tx Controlword 6040", slave + ".Outputs.Controlword", 568, "uint16", 16) ...
        localPdo("targetVelocity60FF", "Tx Target velocity 60FF", slave + ".Outputs.Target velocity", 616, "int32", 32) ...
        localPdo("modeOfOperation6060", "Tx Modes of operation 6060", slave + ".Outputs.Modes of operation", 664, "int8", 8) ...
        localPdo("maxProfileVelocity607F", "Tx Max profile velocity 607F", slave + ".Outputs.Max profile velocity", 688, "uint32", 32)]);
end

function sig = localPdo(key, blockName, signalName, offset, dataType, typeSize)
sig = struct( ...
    'Key', string(key), ...
    'BlockName', string(blockName), ...
    'SignalName', string(signalName), ...
    'Offset', offset, ...
    'DataType', string(dataType), ...
    'TypeSize', typeSize);
end
