function axisCfg = sv660n_axis1()
axisCfg = struct( ...
    'AxisKey', "axis1", ...
    'DriveType', "SV660N", ...
    'SlaveName', "Drive 1 (InoSV660N)", ...
    'EthercatDeviceIndex', 0, ...
    'EthernetPortNumber', 1, ...
    'DefaultSafeVelocity60FF', int32(0), ...
    'DefaultMaxProfileVelocity607F', uint32(1000), ...
    'DefaultIdentificationMaxSpeed60FF', int32(200), ...
    'DefaultIdentificationMaxTravel6064', int32(1000), ...
    'DefaultIdentificationStep6064', int32(100), ...
    'DefaultIdentificationStopBand6064', int32(20), ...
    'DefaultPositionReferenceFile', "data/reference/position_reference_6064.txt", ...
    'DefaultPositionReferenceFeedforwardEnabled', int32(1), ...
    'DefaultPositionCommand6064', int32(0), ...
    'DefaultPositionRateCommand6064', int32(0), ...
    'DefaultPositionVelocityGain', int32(1), ...
    'DefaultPositionVelocityBias', int32(0), ...
    'DefaultCommandDeadband', int32(0), ...
    'DefaultCommandDelaySamples', uint32(0), ...
    'DefaultMaxTrackingSpeed', int32(6000), ...
    'DefaultPositionUnitMillimetersPerCount6064', double(1), ...
    'DefaultPositionLoopKp', int32(0), ...
    'DefaultPositionLoopKi', int32(0), ...
    'DefaultPositionLoopKd', int32(0), ...
    'DefaultPositionLoopSampleTime', double(0.002), ...
    'DefaultPositionLoopIntegratorLimit', int32(0), ...
    'ExpectedModeOfOperation', int8(9));
end
