function axisCfg = sv660n_axis1()
axisCfg = struct( ...
    'AxisKey', "axis1", ...
    'DriveType', "SV660N", ...
    'SlaveName', "Drive 1 (InoSV660N)", ...
    'EthercatDeviceIndex', 0, ...
    'EthernetPortNumber', 1, ...
    'DefaultSafeVelocity60FF', int32(0), ...
    'DefaultMaxProfileVelocity607F', uint32(1000), ...
    'ExpectedModeOfOperation', int8(9));
end
